name: Gitea

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          repository: go-gitea/gitea
          ref: v1.13.7

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.2
        with:
          platforms: arm

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.1.2
        with:
          platforms: arm

      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
