name: Gitea

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          repository: go-gitea/gitea
          ref: v1.13.7

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.2
        with:
          platforms: arm

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.1.2
        with:
          install: true

      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          platforms: arm
