name: Gitea-1.14.4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          repository: go-gitea/gitea
          ref: "v1.14.4"

      - name: Upgrade Alpine 3.13 to 3.14
        shell: bash
        run: |
          sed -i '/alpine/ s/3.13/3.14/' Dockerfile

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1.0.2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1.1.2

      - name: Docker login
        uses: docker/login-action@v1.8.0
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: Build and push images
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          platforms: linux/arm/v6,linux/arm/v7
          push: true
          tags: "stelas/gitea-arm:v1.14.4"
